# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'

steps:
- script: docker build -t $(dockerId)/$(imageName) .  # add options to this command to meet your needs

- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1
