version: '3'
services:

  rockpaperscissors-server:
    build:
      context: .
      dockerfile: Dockerfile-Server
    container_name: rockpaperscissors-server
    environment:
      "ConnectionStrings:DefaultConnection": "Server=tcp:server-p20rps.database.windows.net,1433;Initial Catalog=p20rpsdb;Database=RockPaperScissorsBoom;Persist Security Info=False;User ID=AdminUser;Password=ChangeYoPassword2;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
    ports:
        - "80:80"
